package com.mxinteligente.model.entidades;
// Generated 15/05/2011 12:59:36 PM by Hibernate Tools 3.2.1.GA



/**
 * Categresos generated by hbm2java
 */
public class Categresos  implements java.io.Serializable {


     private CategresosId id;
     private Usuarios usuarios;
     private String nombre;

    public Categresos() {
    }

	
    public Categresos(CategresosId id, Usuarios usuarios) {
        this.id = id;
        this.usuarios = usuarios;
    }
    public Categresos(CategresosId id, Usuarios usuarios, String nombre) {
       this.id = id;
       this.usuarios = usuarios;
       this.nombre = nombre;
    }
   
    public CategresosId getId() {
        return this.id;
    }
    
    public void setId(CategresosId id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


