package com.mxinteligente.model.entidades;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

// Generated 15/05/2011 12:59:36 PM by Hibernate Tools 3.2.1.GA



/**
 * Egresos generated by hbm2java
 */
public class Egresos  implements java.io.Serializable {


     private EgresosId id;
     private Categresos categoria;
     private String concepto;
     private BigDecimal cantidad;
     private Date fecha;
     private BigInteger folio;
     private String contraparte;

    public Egresos() {
    }

	
    public Egresos(EgresosId id) {
        this.id = id;
    }
    public Egresos(EgresosId id, String concepto, BigDecimal cantidad) {
       this.id = id;
       this.concepto = concepto;
       this.cantidad = cantidad;
    }
   
    public EgresosId getId() {
        return this.id;
    }
    
    public void setId(EgresosId id) {
        this.id = id;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }


	public Date getFecha() {
		return fecha;
	}


	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}


	public Categresos getCategoria() {
		return categoria;
	}


	public void setCategoria(Categresos categoria) {
		this.categoria = categoria;
	}


	public BigInteger getFolio() {
		return folio;
	}


	public void setFolio(BigInteger folio) {
		this.folio = folio;
	}


	public String getContraparte() {
		return contraparte;
	}


	public void setContraparte(String contraparte) {
		this.contraparte = contraparte;
	}


	




}


