package com.mxinteligente.model.entidades;
// Generated 15/05/2011 12:59:36 PM by Hibernate Tools 3.2.1.GA



/**
 * EgresosId generated by hbm2java
 */
public class EgresosId  implements java.io.Serializable {


     private int id;
     private int catEgresosUsuariosId;
     private int catEgresosId;

    public EgresosId() {
    }

    public EgresosId(int id, int catEgresosUsuariosId, int catEgresosId) {
       this.id = id;
       this.catEgresosUsuariosId = catEgresosUsuariosId;
       this.catEgresosId = catEgresosId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCatEgresosUsuariosId() {
        return this.catEgresosUsuariosId;
    }
    
    public void setCatEgresosUsuariosId(int catEgresosUsuariosId) {
        this.catEgresosUsuariosId = catEgresosUsuariosId;
    }
    public int getCatEgresosId() {
        return this.catEgresosId;
    }
    
    public void setCatEgresosId(int catEgresosId) {
        this.catEgresosId = catEgresosId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EgresosId) ) return false;
		 EgresosId castOther = ( EgresosId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getCatEgresosUsuariosId()==castOther.getCatEgresosUsuariosId())
 && (this.getCatEgresosId()==castOther.getCatEgresosId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getCatEgresosUsuariosId();
         result = 37 * result + this.getCatEgresosId();
         return result;
   }   


}


