package com.mxinteligente.model.entidades;
// Generated 15/05/2011 12:59:36 PM by Hibernate Tools 3.2.1.GA



/**
 * IngresosId generated by hbm2java
 */
public class IngresosId  implements java.io.Serializable {


     private int id;
     private int catIngresosUsuariosId;
     private int catIngresosId;

    public IngresosId() {
    }

    public IngresosId(int id, int catIngresosUsuariosId, int catIngresosId) {
       this.id = id;
       this.catIngresosUsuariosId = catIngresosUsuariosId;
       this.catIngresosId = catIngresosId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCatIngresosUsuariosId() {
        return this.catIngresosUsuariosId;
    }
    
    public void setCatIngresosUsuariosId(int catIngresosUsuariosId) {
        this.catIngresosUsuariosId = catIngresosUsuariosId;
    }
    public int getCatIngresosId() {
        return this.catIngresosId;
    }
    
    public void setCatIngresosId(int catIngresosId) {
        this.catIngresosId = catIngresosId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IngresosId) ) return false;
		 IngresosId castOther = ( IngresosId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getCatIngresosUsuariosId()==castOther.getCatIngresosUsuariosId())
 && (this.getCatIngresosId()==castOther.getCatIngresosId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getCatIngresosUsuariosId();
         result = 37 * result + this.getCatIngresosId();
         return result;
   }   


}


