package com.mxinteligente.model.entidades;
// Generated 15/05/2011 12:59:36 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Usuarios generated by hbm2java
 */
@XmlRootElement
public class Usuarios  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String nombre;
     private String app;
     private String apm;
     private Integer estatus;
     private String password;
     private Integer nip;
     private Set<Categresos> categresoses = new HashSet<Categresos>(0);
     private Set<Catingresos> catingresoses = new HashSet<Catingresos>(0);
     private BigDecimal saldo;
     private Integer statusTrasnferencia;
     private String token;
     private String rol;
     private String msg;
     private Date fechnac;
     private String domicilio;
     private String clabe;
     private String codigo;
     private List<Movimientos> movimientos;
     private List<Producto> productos;
     private List<OrdenesCompra> ordenes;
     private String isFB;
     
     private String sexo;
    public Integer getStatusTrasnferencia() {
		return statusTrasnferencia;
	}


	public void setStatusTrasnferencia(Integer statusTrasnferencia) {
		this.statusTrasnferencia = statusTrasnferencia;
	}


	public BigDecimal getSaldo() {
		return saldo;
	}


	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}


	public Usuarios() {
    }

	
    public Usuarios(String email) {
        this.email = email;
    }
    public Usuarios(String email, String nombre, String app, String apm, Integer estatus, Set<Categresos> categresoses, Set<Catingresos> catingresoses) {
       this.email = email;
       this.nombre = nombre;
       this.app = app;
       this.apm = apm;
       this.estatus = estatus;
       this.categresoses = categresoses;
       this.catingresoses = catingresoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApp() {
        return this.app;
    }
    
    public void setApp(String app) {
        this.app = app;
    }
    public String getApm() {
        return this.apm;
    }
    
    public void setApm(String apm) {
        this.apm = apm;
    }
    public Integer getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }
    public Set<Categresos> getCategresoses() {
        return this.categresoses;
    }
    
    public void setCategresoses(Set<Categresos> categresoses) {
        this.categresoses = categresoses;
    }
    public Set<Catingresos> getCatingresoses() {
        return this.catingresoses;
    }
    
    public void setCatingresoses(Set<Catingresos> catingresoses) {
        this.catingresoses = catingresoses;
    }


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}


	public String getToken() {
		return token;
	}


	public void setToken(String token) {
		this.token = token;
	}


	public Integer getNip() {
		return nip;
	}


	public void setNip(Integer nip) {
		this.nip = nip;
	}


	public String getRol() {
		return rol;
	}


	public void setRol(String rol) {
		this.rol = rol;
	}


	public String getMsg() {
		return msg;
	}


	public void setMsg(String msg) {
		this.msg = msg;
	}




	public String getDomicilio() {
		return domicilio;
	}


	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}


	public String getClabe() {
		return clabe;
	}


	public void setClabe(String clabe) {
		this.clabe = clabe;
	}


	public Date getFechnac() {
		return fechnac;
	}


	public void setFechnac(Date fechnac) {
		this.fechnac = fechnac;
	}


	public String getCodigo() {
		return codigo;
	}


	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}


	public List<Movimientos> getMovimientos() {
		return movimientos;
	}


	public void setMovimientos(List<Movimientos> movimientos) {
		this.movimientos = movimientos;
	}


	public List<Producto> getProductos() {
		return productos;
	}


	public void setProductos(List<Producto> productos) {
		this.productos = productos;
	}


	public List<OrdenesCompra> getOrdenes() {
		return ordenes;
	}


	public void setOrdenes(List<OrdenesCompra> ordenes) {
		this.ordenes = ordenes;
	}


	


	public String getSexo() {
		return sexo;
	}


	public void setSexo(String sexo) {
		this.sexo = sexo;
	}


	public String getIsFB() {
		return isFB;
	}


	public void setIsFB(String isFB) {
		this.isFB = isFB;
	}




}


